Updates to UI.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,5 +1,20 @@
 # /bin/bash
-ADDR="192.168.86.31" # 31 FOR 3.1[41592] (PI)
+
+## Determine to which network to attach
+X="$(ifconfig)"
+if echo $X | grep -q "192.168.86"
+then
+   echo "Cantopilot is on home network"
+   ADDR="192.168.86.31" # 31 FOR 3.1[41592] (PI)
+elif echo $X | grep -q "192.160.10"
+then
+   echo "Cantopilot is its own access point"
+   ADDR="192.160.10.1" 
+else
+   echo "Can't find cantopilot"
+   exit 1
+fi
+
 echo "Deploying to address $ADDR"
 cd /Users/avrouwenve/Private/adrianAutoPilot
 if [ "$1" == "" ]
