Checkpoint.
* Compass works when level.
* Accelerometer works
* Gyro works
* Rudder limits work
* Brain turns rudder in proper direction
* Setting and persisting of gains works

Still TODO:

* Add tilt-compensation to compass
* Actual in-the-water tests to better couple boat heading with rudder action.
* Add compass debug / calibration page

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -22,7 +22,8 @@ then
    export timestamp=$(date +%Y%m%d%H%M%S)
    echo "Using timestamp $timestamp"
    target=deployment_$timestamp.tar
-   tar --exclude "__pycache__" --exclude logs --exclude archive -cf $target configuration modules run_*.sh web 
+   tar --exclude "__pycache__" --exclude logs --exclude archive --exclude test_config* --exclude *_overrides.yaml --exclude logging.conf -cf $target configuration modules run_*.sh web
+   # tar --exclude "__pycache__" --exclude logs --exclude archive --exclude test_config* -cf $target configuration modules run_*.sh web
    scp $target tc@$ADDR:/mnt/mmcblk0p2/apps/adrianAutoPilot/$target
 else
    target=$1
@@ -31,9 +32,9 @@ fi
 ssh tc@$ADDR "(cd /mnt/mmcblk0p2/apps/adrianAutoPilot \
   && touch configuration modules testing web \
   && sudo chmod -R ugo+w modules testing web \
-  && rm -fr configuration modules testing web Documents *.sh \
+  && rm -fr modules testing web Documents *.sh \
   && tar -xf $target \
   && rm -f $target \
   && echo "Deployment of $target to tc@$ADDR complete." \
-  && echo "NOTE To persist run_webserver.sh, run filetool.sh -b" )|| echo Deployment of $target to tc@$ADDR FAILED!"
+  && echo "NOTE To persist deployment, run filetool.sh -b" )|| echo Deployment of $target to tc@$ADDR FAILED!"
 
